modLoader="javafml"
loaderVersion="[44,)"
license="MIT License"
# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]]
modId="serilis"
version="0.0.1"
displayName="Serilis"
# A URL to query for updates for this mod. See the JSON update specification https://docs.minecraftforge.net/en/latest/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="logo.png"
credits="Dev and Artist: Claraisplaying, Localisation: Int22" #optional
authors="Claraisplaying"
description='''
Serilis is an ambitious tech and progression mod, starting from the stone age and possibly ending to the space age.
A world to fight and adapt to, flint tools, engineering, machines, vehicles, clockwork, steam technology, dieselpunk, and more, although these are just ambitions, shall you join us in exploring the potential of this mod?
'''
[[dependencies.serilis]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.serilis]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.21)"
    ordering="NONE"
    side="BOTH"
